### ISSUE TITLE
Pod not usable with dynamic frameworks through cocoapods

### ISSUE THREAD

**Issue by elsesiy** [cryptomator/cryptomator-objc-cryptor#1]
Hi guys,

first of all: awesome work!

I was just playing around with the repository in a swift project but couldn't get it to work with my current podfile since there's a transitive dependencies that uses static binaries which can't be provided as a dynamic framwork with `use_frameworks!` through cocoapods. 

I found the OpenSSL-Universal pod you rely on to be the cause, so I guess you could either fork it and restructure the project, find an alternative ssl implementation for iOS or I could contact the developer and ask for their support?

Thanks!

**Comment by tobihagemann** [comment]
Thanks! Yes, you're right. OpenSSL is a static library and causes the issue, when using `use_frameworks!`. Haven't really thought of it, because I'm personally not a big fan of dynamic frameworks (it caused more issues than it solved). But you're absolutely right that this should be solved.
- I'm not completely sure about forking OpenSSL and restructuring the project. It's easier to maintain this project, if we wouldn't do so. Unless, there is a way to do that and keep the "easy maintenance".
- If I'm not mistaken, we're using OpenSSL for AES CTR und AES Key Wrap. I don't think we can find an alternative implementation that we would consider "secure".
- It looks like this question has been already asked here: https://github.com/krzyzanowskim/OpenSSL/issues/22

I'm not sure how to solve this properly. Probably your first suggestion could be the way to go, even though I'm not completely satisfied with it.

In the meantime you could fork this project and integrate OpenSSL manually.
