### ISSUE TITLE
Encrypt images

### ISSUE THREAD

**Issue by CavalcanteLeo** [cryptomator/cryptomator-objc-cryptor#2]
Is it possible to encrypt images, then save the encrypted image into the documents bundle?

**Comment by tobihagemann** [comment]
Yes, it's possible. Not sure if this library is maybe overkill for your purposes but you could absolutely achieve that.

As taken from the README, at first, you need to initialize the cryptor and create a master key:

https://github.com/cryptomator/cryptomator-objc-cryptor#create-new-cryptor--master-key

Make sure to persist the masterkey:

https://github.com/cryptomator/cryptomator-objc-cryptor#setomasterkey

You can then encrypt data like this:

https://github.com/cryptomator/cryptomator-objc-cryptor#file-content-encryption

We don't have an API for `NSData` because this library is for file-based encryption.

If the masterkey already exists, you can create the cryptor like this:

https://github.com/cryptomator/cryptomator-objc-cryptor#create-cryptor-from-existing-master-key

HTH
